# Generated by Django 4.1.3 on 2022-12-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_groups_users_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
