# Generated by Django 4.1.3 on 2022-12-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_is_admin_users_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='users',
            name='realname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
