# Generated by Django 4.1.3 on 2022-12-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
